@startuml getAllCategories
class CategoriesController {
  + getAllCategories() : Response
}

class CategoriesService {
  + fetchAllCategories() : List<Category>
}

class Category {
  - category_id : int
  - name : string
  - description : string
  - created_at : timestamp
  - updated_at : timestamp
}

class CategoriesRepository {
  + getAllCategoriesFromDB() : List<Category>
}

CategoriesController --> CategoriesService
CategoriesService --> CategoriesRepository
CategoriesRepository --> Category
@enduml
